name: gender_selector
description: A Flutter Package for gender selector widget for the app. Using this package you can allow the user to select the gender by the beautiful widget. Show your love on this package.
version: 1.0.0
author: Dhruvil Patel <dhruvilscreation@gmail.com>
homepage: https://github.com/dhruvil2000/gender_selector_flutter

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  assets:
    - assets/male.png
    - assets/female.png